// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑

// @ts-nocheck
/* eslint-disable */
export type CoercedEnvSchema = {
  /**
   * **DATABASE_URL** 🔐 _sensitive_
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  DATABASE_URL: string;

  /**
   * **NEXT_PUBLIC_SITE_URL**
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  NEXT_PUBLIC_SITE_URL: string;

  /**
   * **BETTER_AUTH_SECRET** 🔐 _sensitive_
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  BETTER_AUTH_SECRET: string;

  /**
   * **BETTER_AUTH_URL**
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  BETTER_AUTH_URL: string;

  /**
   * **RESEND_API_KEY** 🔐 _sensitive_
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  RESEND_API_KEY: string;

  /**
   * **RESEND_FROM** 🔐 _sensitive_
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  RESEND_FROM: string;

  /**
   * **OWNER_EMAIL**
   * Adresses email (identifiants, pas des secrets) : elles transitent
   * légitimement dans les réponses d'auth (user.email). On les marque
   * non sensibles pour éviter le faux positif du scan anti-fuite de varlock
   * (« DETECTED LEAKED SENSITIVE CONFIG ») qui bloquait la connexion admin.
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  OWNER_EMAIL: string;

  /**
   * **ADMIN_EMAIL**
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  ADMIN_EMAIL: string;

  /**
   * **NEXT_PUBLIC_WAVE_MERCHANT_ID**
   * Identifiant marchand Wave (ex: M_ci_MTkvxiIpuylE). Utilisé pour construire
   * les liens de paiement `https://pay.wave.com/m/<ID>/c/ci/?amount=<montant>`.
   * Si vide, les messages Wave WhatsApp incluent un placeholder à compléter.
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  NEXT_PUBLIC_WAVE_MERCHANT_ID: string;

  /**
   * **MCP_API_KEY** 🔐 _sensitive_
   * Jeton d'accès « machine » au serveur MCP (/api/mcp), passé en
   * `Authorization: Bearer <token>`. Secret (sensible par défaut). OPTIONNEL :
   * pour les clients qui gèrent leurs en-têtes (Claude Code CLI, curl). Les
   * clients Claude web/mobile passent par OAuth (rôle ADMIN) — voir
   * `app/api/mcp/README.md`. Si non configurée, seul OAuth est actif. Générer une
   * valeur aléatoire forte, ex. `openssl rand -hex 32`.
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  MCP_API_KEY?: string;

  /**
   * **CRON_SECRET** 🔐 _sensitive_
   * Secret bearer OPTIONNEL pour déclencher le rappel d'inventaire depuis un cron
   * externe : `POST /api/inventory/reminder-check` avec l'en-tête
   * `Authorization: Bearer <CRON_SECRET>`. Si non configurée, la route est inerte
   * (404). Générer une valeur aléatoire forte, ex. `openssl rand -hex 32`.
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  CRON_SECRET?: string;

  /**
   * **NEXT_PUBLIC_VAPID_PUBLIC_KEY**
   * Clé publique VAPID (notifications push backoffice). Avec VAPID_PRIVATE_KEY,
   * active l'abonnement push depuis le dashboard (nouvelle commande, commande
   * prête). Si absente, la fonctionnalité reste inerte. Générer la paire avec
   * `pnpm exec web-push generate-vapid-keys`.
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  NEXT_PUBLIC_VAPID_PUBLIC_KEY?: string;

  /**
   * **VAPID_PRIVATE_KEY** 🔐 _sensitive_
   * Clé privée VAPID associée à NEXT_PUBLIC_VAPID_PUBLIC_KEY. Secret (sensible par
   * défaut) : ne jamais exposer côté client.
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  VAPID_PRIVATE_KEY?: string;

  /**
   * **VAPID_SUBJECT**
   * Identifiant de contact VAPID (obligatoire par la spec Web Push), ex.
   * `mailto:contact@ebacoffeeshop.com`.
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  VAPID_SUBJECT?: string;

  /**
   * **NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME**
   * Nom du cloud Cloudinary. Non sensible : nécessaire côté navigateur pour
   * poster directement vers https://api.cloudinary.com/v1_1/<cloud>/... (upload
   * signé, sans passer par notre serveur). Dashboard Cloudinary > cloud name.
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: string;

  /**
   * **NEXT_PUBLIC_CLOUDINARY_API_KEY**
   * Clé API Cloudinary. Non secrète en soi (seul CLOUDINARY_API_SECRET l'est) :
   * nécessaire côté navigateur pour construire le POST d'upload signé.
   * Dashboard Cloudinary > Settings > API Keys.
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  NEXT_PUBLIC_CLOUDINARY_API_KEY: string;

  /**
   * **CLOUDINARY_API_SECRET** 🔐 _sensitive_
   * Secret API Cloudinary, sert à SIGNER les paramètres d'upload côté serveur
   * (dossier, transformation, formats autorisés). Ne jamais exposer côté
   * client. Dashboard Cloudinary > Settings > API Keys.
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  CLOUDINARY_API_SECRET: string;

  /**
   * **CLOUDINARY_FOLDER_PREFIX**
   * Préfixe de dossier Cloudinary, isole dev/staging/prod dans le même compte
   * (ex. "eba-coffee-shop"). Défaut si absent : "eba-coffee-shop-dev".
   * ![icon](data:image/svg+xml;utf-8,Host%20not%20in%20allowlist%3A%20api.iconify.design.%20Add%20this%20host%20to%20your%20network%20egress%20settings%20to%20allow%20access.)
   */
  CLOUDINARY_FOLDER_PREFIX?: string;
};

type _CoercedEnvSchema_cb99056c = CoercedEnvSchema;

declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<_CoercedEnvSchema_cb99056c> {}
  export interface PublicTypedEnvSchema extends Readonly<
    Pick<
      _CoercedEnvSchema_cb99056c,
      | 'NEXT_PUBLIC_SITE_URL'
      | 'BETTER_AUTH_URL'
      | 'OWNER_EMAIL'
      | 'ADMIN_EMAIL'
      | 'NEXT_PUBLIC_WAVE_MERCHANT_ID'
      | 'NEXT_PUBLIC_VAPID_PUBLIC_KEY'
      | 'VAPID_SUBJECT'
      | 'NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME'
      | 'NEXT_PUBLIC_CLOUDINARY_API_KEY'
      | 'CLOUDINARY_FOLDER_PREFIX'
    >
  > {}
}

export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]: CoercedEnvSchema[Property] extends string
    ? CoercedEnvSchema[Property]
    : CoercedEnvSchema[Property] extends boolean
      ? 'true' | 'false'
      : string;
};

type _EnvSchemaAsStrings_cb99056c = EnvSchemaAsStrings;
declare global {
  // add types for global import.meta.env
  interface ImportMetaEnv extends _EnvSchemaAsStrings_cb99056c {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }

  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends _EnvSchemaAsStrings_cb99056c {}
  }
}
